name: hexlet-check

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npm ci
      - run: npm run build
      - run: make lint
      - uses: actions/checkout@v2
      - name: Hexlet project check
        uses: hexlet/project-action@release
      
